version: '3.8'

services:
  db:
    image: postgres:15
    container_name: trailblaze_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trailblaze
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trailblaze_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/trailblaze
      - DOCKER_ENV=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trailblaze_scraper
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/trailblaze
      - DOCKER_ENV=true
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    command: python -m scrapers.run_scrapers aerc_calendar

  manage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trailblaze_manage
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/trailblaze
      - DOCKER_ENV=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    command: tail -f /dev/null  # Keep container running

  test:
    build: .
    command: pytest
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@test-db:5432/test_trailblaze
      - PYTHONPATH=/app
      - AERC_GEMINI_API_KEY=test_key
      - AERC_DEBUG_MODE=true
      - AERC_REFRESH_CACHE=true
    depends_on:
      - test-db

  test-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_trailblaze
    ports:
      - "5433:5432"  # Different port to avoid conflicts
      
volumes:
  postgres_data:
