"""align_location_field_names

Revision ID: 7150513a9155
Revises: rename_date_columns
Create Date: 2025-03-15 21:02:11.545201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7150513a9155'
down_revision = 'rename_date_columns'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_date_start', table_name='events')
    op.drop_index('ix_events_id', table_name='events')
    op.drop_index('ix_events_region', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('organizer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('flyer_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('distances', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ride_manager', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manager_contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manager_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manager_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('judges', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('directions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('map_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.create_index('ix_events_region', 'events', ['region'], unique=False)
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.create_index('ix_events_date_start', 'events', ['date_start'], unique=False)
    # ### end Alembic commands ###
